#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#pkill feh 
#${HOME}/.config/wall.sh &

#pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
#${HOME}/.config/picom/picom.conf &

${HOME}/.screenlayout/layout.sh &

#pkill polybar
#${HOME}/.config/polybar/launch.sh &

#wallpaper=${HOME}/Pictures/Wall/wal4.png
#wal -n -q -i "$wallpaper" &
#feh --bg-scale "$wallpaper 
   
${HOME}/.config/wall.sh &

#wal -R &

pkill dunst 
dunst &
